version: '3.3'

services:
   prod:
     image: microblog:latest
     ports:
       - "8000:5000"
     volumes:
       - ./app:/home/microblog/app
     restart: always
     environment:
       FLASK_APP: microblog.py

   test:
     image: test:latest
     volumes:
       - ./app:/home/microblog/app
       - ./tests:/home/microblog/tests
     

