# Python CircleCI 2.0 configuration file
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: poand18/microblog
    docker:
    - image: circleci/buildpack-deps:stretch

jobs:
  test:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install dev dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install-dev
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make validate
            make test-unit
            make test-integration
            #echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            #sudo docker push mangepong/microblog:latest
    
    build_image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest -f docker/Dockerfile_prod .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
