# Python CircleCI 2.0 configuration file
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: mangepong/microblog
    docker:
    - image: circleci/buildpack-deps:stretch
jobs:
  test:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            make install-dev
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
            #echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            #sudo docker push mangepong/microblog:latest
    
    build_image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t microblog:latest -f docker/Dockerfile_prod .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar mircoblog
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
