# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            make install-dev
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            sudo docker push mangepong/microblog:latest
