FROM python:3.6-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py no-statsd.sh ./

RUN python -m venv .venv
ENV FLASK_APP microblog.py
RUN .venv/bin/pip3 install -r requirements.txt
RUN apk --update upgrade

RUN chmod +x no-statsd.sh

RUN chown -R microblog:microblog ./
USER microblog

EXPOSE 5000
ENTRYPOINT ["./no-statsd.sh"]