FROM python:3.6-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY requirements requirements
COPY requirements.txt microblog.py test.sh ./
COPY Makefile Makefile
COPY .pylintrc .pylintrc
COPY pytest.ini pytest.ini


RUN apk --no-cache add alpine-sdk=1.0-r0

RUN python -m venv .venv
ENV FLASK_APP microblog.py
RUN .venv/bin/pip3 install -r requirements/test.txt
RUN make clean
RUN chmod +x test.sh

RUN chown -R microblog:microblog ./
USER root

ENTRYPOINT ["./test.sh"]
